db/migrate/20250114185426_drop_table_events.rb
db/migrate/20250114185853_remove_events_references_from_favorites.rb
db/schema.rb

Co-authored-by: CristianoSantan <cristiano_santana@live.com>
Co-authored-by: JoaoCasteloBranco <joao.castelo.medeiros@gmail.com>
Co-authored-by: César Faustino <cesar.faustino@fatec.sp.gov.br>
Co-authored-by: SamuelRocha91 <samuel_sr@hotmail.com.br>
Co-authored-by: Gabriel-T-P <gabrielthiago2000@hotmail.com>

Eliminada tabela de eventos, e chaves estrangerias

---

Gemfile
Gemfile.lock
app/models/event.rb
app/models/favorite.rb
config/initializers/locale.rb
config/locales/devise.pt-BR.yml
config/locales/pt-BR.yml
spec/models/event_spec.rb
spec/models/favorite_spec.rb
spec/models/profile_spec.rb
spec/models/user_spec.rb
spec/support/devise_methods.rb
spec/support/factory_bot.rb
spec/support/shoulda-matchers.rb

Co-authored-by: CristianoSantan <cristiano_santana@live.com>
> Co-authored-by: JoaoCasteloBranco <joao.castelo.medeiros@gmail.com>
> Co-authored-by: César Faustino <cesar.faustino@fatec.sp.gov.br>
> Co-authored-by: SamuelRocha91 <samuel_sr@hotmail.com.br>
> Co-authored-by: Gabriel-T-P <gabrielthiago2000@hotmail.com>

Adicionado configurações de Faraday, I18n, Shouldamatchers e devise

---

app/controllers/events_controller.rb
app/controllers/home_controller.rb
app/models/event.rb
app/views/home/index.html.erb
config/locales/views/favorites/home.pt-BR.yml
config/routes.rb
spec/system/events/user_view_events_details_spec.rb
spec/system/user_visit_root_path_spec.rb

Adicionados testes para verificar se o visitante vê a lista de eventos na homepage, consumindo uma API externa, e se consegue acessar a tela de detalhes do evento assim como sua implementação

Adicionado lista de eventos na homepage, e acceso a tela de show

---

app/models/event.rb
app/views/events/_event.html.erb
app/views/events/index.html.erb
app/views/favorites/index.html.erb
spec/models/event_spec.rb

Cria estilo de css para página de favoritos e refatora testes acrescentando parametros de inicio e fim de evento
Resolve #37

Estiliza páginas e refatora codigo

---

app/controllers/application_controller.rb
app/controllers/favorites_controller.rb
app/views/events/_event.html.erb
app/views/events/index.html.erb
app/views/shared/_nav.html.erb
config/locales/views/events/en.yml
config/locales/views/events/pt-BR.yml
config/routes.rb
spec/requests/favorites/user_create_favorites_request_spec.rb
spec/requests/favorites/user_delete_favorite_request_spec.rb
spec/requests/profile/user_update_profile_spec.rb
spec/requests/social_link/user_create_social_link_spec.rb
spec/system/events/user_sees_events_details_spec.rb
spec/system/events/visitant_sees_events_details_spec.rb
spec/system/favorites/user_view_favorites_spec.rb
spec/system/languages/user_change_language_spec.rb
spec/system/profile/links/user_add_new_social_link_spec.rb
spec/system/profile/user_edit_profile_spec.rb
spec/system/profile/user_view_profile_spec.rb

Utilizando do  I18n foi feito um sistema de alteração de idioma, com português e inglês.
Tela Principal, com botões de troca de idioma na Nav
RESOLVE #41

Usuário muda idioma do aplicativo

---

app/assets/stylesheets/application.tailwind.css
app/controllers/batches_controller.rb
app/models/batch.rb
app/models/event.rb
app/services/events_api_service.rb
app/views/batches/index.html.erb
app/views/events/show.html.erb
config/locales/views/baches/pt-BR.yml
config/locales/views/batches/pt-BR.yml
spec/factories/batch.rb
spec/factories/events.rb
spec/models/batch_spec.rb
spec/rails_helper.rb
spec/system/batches/user_view_batches_spec.rb
spec/system/events/user_sees_events_details_spec.rb
spec/system/events/visitant_sees_events_details_spec.rb

Adicionada nova funcionalidade, para o usuário acessar na tela de listagem de tipos de ingressos
Foto da tela de listagem:
#10

Usuario visualiza tipos de ingresso a traves da tela de detalhes do evento

---

app/controllers/batches_controller.rb
app/controllers/events_controller.rb
app/views/batches/index.html.erb
app/views/events/show.html.erb
config/locales/custom/batch/en.yml
config/locales/custom/batch/pt-BR.yml
config/locales/custom/event/pt-BR.yml
config/locales/custom/generic/en.yml
config/locales/custom/generic/pt-BR.yml
config/locales/views/batches/en.yml
config/locales/views/batches/pt-BR.yml

Corrige traduções do shoe de eventos, do model de batches e no controller de eventos.
Resolve #58

Correção de traduções I18n

---

app/controllers/tickets_controller.rb
app/models/batch.rb
app/models/ticket.rb
app/views/tickets/new.html.erb
config/locales/models/ticket/pt-BR.yml
config/routes.rb
db/migrate/20250123202504_change_ticket_status_to_boolean.rb
db/migrate/20250123203216_rename_column_status_to_column_status_in_tickets.rb
db/schema.rb
spec/factories/batch.rb
spec/factories/tickets.rb
spec/models/ticket_spec.rb
spec/requests/tickets/user_purchases_ticket_spec.rb
spec/system/tickets/user_buys_ticket_spec.rb

- Usuário consegue realizar compra de ingresso selecionando método de pagamento
-  Desenvolvimento do model Ticket com validações
- Adição de testes unitários do model Ticket, testes de sistema para o fluxo de comprar de ingresso e de request para proteção das rotas de ciração de ingresso.
resolve #11

Usuário consegue realizar compra

---

app/controllers/reminders_controller.rb
app/views/events/show.html.erb
config/locales/models/favorite/en.yml
config/locales/views/reminders/en.yml
config/locales/views/reminders/pt-BR.yml
config/routes.rb
spec/requests/reminders/user_delete_reminder_ticket_spec.rb
spec/system/reminders/user_remove_reminder_ticket_spec.rb

Traduções para flash messages, testa cenarios de usuario logado e não logado, teste de tentativa de excluir lembrete com id inexistente, rota de remoção de lembrete e action.
Resolve #66

Cria funcionalidade de remover lembrete

---

app/views/tickets/new.html.erb

Estiliza página de compra de ingressos

---

app/controllers/reminders_controller.rb
app/mailers/reminders_mailer.rb
app/views/reminders_mailer/ticket_reminder.html.erb
config/environments/test.rb
config/locales/views/reminders_mailer/en.yml
config/locales/views/reminders_mailer/pt-BR.yml
spec/jobs/reminder_mailer_spec.rb
spec/mailers/reminders_mailer_spec.rb
spec/system/reminders/user_add_reminder_ticket_spec.rb

Cria teste de job para verificar se o email é enfileirado, cria teste de email pra verificar se ele esta sendo construido com argumentos corretos e cria teste de sistema com mocks pra verificar chamada do mailer. 
Resolve #14

Implementa funcionalidade de envio de email futuro para lembretes de ingressos

---

app/assets/stylesheets/application.tailwind.css
app/helpers/application_helper.rb
app/services/events_api_service.rb
app/views/batches/index.html.erb
app/views/events/_event.html.erb
app/views/events/index.html.erb
app/views/favorites/index.html.erb
app/views/tickets/new.html.erb
config/locales/en.yml
config/locales/views/batches/en.yml

Implementa melhoria de css, tradução monetária e select de pagamentos

---

app/controllers/batches_controller.rb
app/controllers/events_controller.rb
app/services/events_api_service.rb
app/views/events/index.html.erb
app/views/favorites/index.html.erb
config/routes.rb
spec/system/batches/user_view_batch_spec.rb
spec/system/batches/user_view_batches_spec.rb
spec/system/events/user_sees_events_details_spec.rb
spec/system/events/visitant_sees_events_details_spec.rb
spec/system/reminders/user_add_reminder_ticket_spec.rb
spec/system/reminders/user_remove_reminder_ticket_spec.rb

Refatora testes e implementa nova rota customizada de eventos. 
Resolve #43

Cria rota personalizada com nome do evento

---

app/controllers/reminders_controller.rb
app/models/reminder.rb
app/views/events/show.html.erb
config/locales/views/reminders/en.yml
config/locales/views/reminders/pt-BR.yml
spec/models/reminder_spec.rb
spec/requests/reminders/user_create_reminder_ticket_spec.rb
spec/system/reminders/user_add_reminder_ticket_spec.rb
spec/system/reminders/user_remove_reminder_ticket_spec.rb

**Descrição**: 
- Refatoração da lógica de criação de um Reminder no Controller. Checando a existência de um lote.
- Alteração na view para só ser possível visualizar o botão de criação de um Lembrete caso o Evento possua um model.
- Adequação dos testes. 
resolve #90

Refatoração da lógica de Lembrente

---

README.md
app/assets/stylesheets/application.css
app/assets/stylesheets/application.tailwind.css
app/views/batches/index.html.erb
app/views/events/index.html.erb
app/views/events/show.html.erb
app/views/home/index.html.erb
app/views/layouts/application.html.erb
app/views/profiles/edit.html.erb
app/views/profiles/show.html.erb
app/views/shared/_nav.html.erb
app/views/social_links/new.html.erb
config/environments/development.rb
config/locales/custom/event/en.yml
config/locales/views/batches/en.yml
config/locales/views/batches/pt-BR.yml
config/locales/views/favorites/en.yml
config/locales/views/favorites/pt-BR.yml
config/locales/views/profile/en.yml
config/locales/views/profile/pt-BR.yml
config/locales/views/profile/social_link/en.yml
config/locales/views/profile/social_link/pt-BR.yml
config/locales/views/shared/nav/en.yml
config/locales/views/shared/nav/pt-BR.yml
config/locales/views/tickets/en.yml
spec/system/batches/user_view_batches_spec.rb
spec/system/favorites/user_add_event_to_favorites_spec.rb
spec/system/languages/user_change_language_spec.rb
spec/system/profiles/user_edit_profile_spec.rb

Cria dropdown de tradução, botões de voltar, testes, traduções e ajustes de css
Resolve #93

Cria dropdown de tradução e ajustes de css

---

app/models/event.rb
app/services/events_api_service.rb
app/views/events/show.html.erb
db/migrate/20250130140456_remove_event_id_from_favorites.rb
db/migrate/20250130140547_add_event_id_to_favorites.rb
db/migrate/20250130141302_remove_event_id_from_reminders.rb
db/migrate/20250130141330_add_event_id_to_reminders.rb
db/migrate/20250130142517_remove_event_id_from_tickets.rb
db/migrate/20250130142528_add_event_id_to_tickets.rb
db/schema.rb
spec/factories/events.rb
spec/models/batch_spec.rb
spec/models/event_spec.rb
spec/services/events_api_service_spec.rb
spec/support/json/error_events_list.json
spec/support/json/events_for_sale_list.json
spec/support/json/events_list.json
spec/system/tickets/user_view_my_events_spec.rb
spec/system/tickets/user_view_purchased_tickets_spec.rb

Modificação de models, views e testes de eventos para adaptação a api de eventos
Modificação de diferentes models no active record para adaptar a nova id do evento
tela de eventos:
tela de detalhes do evento:
tela de meus favoritos:
#77

Adaptação do codigo para receber dados do app de eventos

---

app/views/events/show.html.erb
config/locales/views/events/en.yml
config/locales/views/events/pt-BR.yml
spec/system/feed/user_view_feed_spec.rb

- Usuário vê feed de postagens de um evento. Precisa ser participante do evento e estar autenticado.
resolve #100

Implementa feed de eventos com restrições de participante

---

app/views/posts/new.html.erb
app/views/posts/show.html.erb
config/locales/views/posts/en.yml
config/locales/views/posts/pt-BR.yml
spec/system/posts/user_view_post_spec.rb

Estiliza páginas de posts

---

app/controllers/dashboard_controller.rb
app/models/event.rb
app/views/dashboard/index.html.erb
app/views/posts/_post.html.erb
config/locales/views/dashboard/en.yml
config/locales/views/dashboard/pt-BR.yml
config/locales/views/posts/en.yml
config/locales/views/posts/pt-BR.yml
spec/system/dashboard/user_view_dashboard_spec.rb

Acrescenta nome ao feed de posts e cria hipótese de inexistência de postagens, testes e css
Resolve #114

Acrescenta nome ao feed de posts e cria hipótese de inexistência de postagens

---

app/views/my_events/index.html.erb
app/views/my_events/show.html.erb
config/locales/en.yml
config/locales/pt-BR.yml
config/locales/views/events/en.yml
config/locales/views/events/pt-BR.yml
config/locales/views/my_events/en.yml
config/locales/views/my_events/pt-BR.yml
spec/system/tickets/user_view_my_events_spec.rb
spec/system/tickets/user_view_purchased_tickets_spec.rb

Estiliza página de meus eventos e meus ingressos

---

app/helpers/application_helper.rb
app/views/comments/_new.html.erb
app/views/events/show.html.erb
app/views/posts/_form.html.erb
app/views/posts/show.html.erb
config/locales/views/posts/en.yml

Estiliza show de posts e corrige lógica de conversão de valores

---

app/controllers/api/v1/batches_controller.rb
app/models/batch.rb
spec/requests/apis/tickets/tickets_api_spec.rb

Mudança de recepção de parâmetros no controller dos lotes na api 
Removido erro na requisição 
e refatoração de testes
Resolve #129

Removido erro de requisição ao consumir um lote de um evento

---

app/controllers/feedbacks_controller.rb
app/models/feedback.rb
app/views/feedbacks/index.html.erb
app/views/feedbacks/new.html.erb
app/views/my_events/index.html.erb
config/locales/models/feedback/en.yml
config/locales/models/feedback/pt-BR.yml
config/locales/models/feedback/pt-BT.yml
config/locales/views/feedbacks/en.yml
config/locales/views/feedbacks/pt-BR.yml
config/locales/views/my_events/en.yml
config/locales/views/my_events/pt-BR.yml
config/routes.rb
db/migrate/20250203210641_create_feedbacks.rb
db/migrate/20250203215934_rename_column_coment_in_feedbacks_coment_to_comment.rb
db/schema.rb
spec/factories/feedbacks.rb
spec/models/feedback_spec.rb
spec/requests/feedbacks/user_create_feedback_request_spec.rb
spec/system/feedbacks/user_add_feedback_spec.rb

Criação de formulário de um feedback
Criação de página para visualização dos feedbacks
Criação do model e validações
Resolve #21

Usuário retorna feedback de evento finalizado

---

app/controllers/events_controller.rb
app/models/event.rb
app/services/events_api_service.rb
app/views/events/index.html.erb
config/locales/views/events/en.yml
config/locales/views/events/pt-BR.yml
spec/models/event_spec.rb
spec/services/events_api_service_spec.rb
spec/system/events/user_view_events_spec.rb

Cria busca personalizada de evento e testes de sistema e de requisição
Resolve #128

Cria busca personalizada de evento

---

app/helpers/application_helper.rb
app/views/batches/index.html.erb
app/views/feedbacks/new.html.erb
app/views/posts/_form.html.erb
app/views/posts/show.html.erb
app/views/profiles/edit.html.erb
app/views/shared/_errors_messages.html.erb
app/views/social_links/new.html.erb
app/views/tickets/new.html.erb
app/views/tickets/show.html.erb
config/locales/custom/button/en.yml
config/locales/custom/button/pt-BR.yml
config/locales/views/profile/pt-BR.yml
config/locales/views/profile/social_link/pt-BR.yml
spec/system/batches/user_view_batches_spec.rb
spec/system/profiles/links/user_add_new_social_link_spec.rb
spec/system/profiles/user_edit_profile_spec.rb

Adicionado helper para botões de voltar, testes e modificação nas telas 
Resolve #132

Adiciona botões de voltar

---

app/models/schedule.rb
app/models/schedule_item.rb
spec/models/event_spec.rb
spec/models/schedule_items_spec.rb

Adiciona atributo code a item de agenda e refatoração de testes
Resolve #155

Adicionado atributo code a iten de agenda

---

app/assets/stylesheets/application.tailwind.css
app/views/announcements/_announcement.html.erb
app/views/announcements/_announcement_list_item.html.erb
app/views/events/show.html.erb
config/locales/views/announcement/en.yml
config/locales/views/announcement/py-BR.yml
config/locales/views/events/pt-BR.yml
spec/system/annoucement/user_view_annoucements_spec.rb

Dá destaque aos comunicados e incrementa testes
Azulou
Resolve #143

Estiliza comunicados, dá destaque e realiza testes

---

app/services/speakers_api_service.rb
spec/services/speakers_api_service_spec.rb

implementa os testes de sucesso e falha da api

feat/ adiciona serviço de comunicação com a API de Palestrantes 

---

app/assets/stylesheets/application.tailwind.css
app/controllers/events_controller.rb
app/helpers/application_helper.rb
app/models/speaker.rb
app/services/speakers_api_service.rb
app/views/events/show.html.erb
app/views/speakers/_speaker_card.html.erb
config/locales/custom/speaker/en.yml
config/locales/custom/speaker/pt-BR.yml
config/locales/views/events/en.yml
config/locales/views/events/pt-BR.yml
spec/factories/schedule_item.rb
spec/factories/speaker.rb
spec/models/speaker_spec.rb
spec/services/speakers_api_service_spec.rb
spec/spec_helper.rb
spec/system/events/user_sees_events_details_spec.rb
spec/system/events/visitant_sees_events_details_spec.rb
spec/system/profiles/user_edit_profile_spec.rb

Insere card de palestrantes na página de detalhes de um evento, testes, traduções e css.
Resolve #46

Integração: insere card de palestrantes no detalhe de evento

---

app/controllers/events_controller.rb
app/models/announcement.rb
app/models/event.rb
app/services/events_api_service.rb
app/views/announcements/_announcement_list_item.html.erb
app/views/events/show.html.erb
spec/factories/announcements.rb
spec/factories/events.rb
spec/models/announcements_spec.rb
spec/models/event_spec.rb
spec/services/events_api_service_spec.rb
spec/support/json/error_events_list.json
spec/support/json/events_list.json
spec/system/announcement/user_view_annoucements_spec.rb
spec/system/announcement/user_view_announcement_details_spec.rb

Refatora POROS, testes e views para recebimento de announcements
Resolve #169

Refatora conexão com a Api de eventos para receber comunicados

---

app/assets/stylesheets/application.tailwind.css
app/controllers/posts_controller.rb
app/models/post.rb
app/views/posts/show.html.erb
config/locales/views/posts/en.yml
config/locales/views/posts/pt-BR.yml
config/routes.rb
spec/requests/posts/user_delete_post_spec.rb
spec/system/posts/user_delete_post_spec.rb

Participante de evento pode deletar postagem em que é dono.
Infelizmente eu não conseguir pegar a imagem do botão de deletar.
Resolve #97

Usuário deleta postagem

---

app/models/user.rb
db/migrate/20250207194954_add_code_to_user.rb
db/schema.rb
spec/factories/users.rb
spec/models/user_spec.rb

Adiciona atributo code ao model de user
Resolve #177

adiciona code ao model de user

---

app/models/curriculum.rb
app/views/schedule_items/show.html.erb
config/locales/views/schedule_items/en.yml
config/locales/views/schedule_items/pt-BR.yml
spec/models/curriculum_spec.rb
spec/requests/schedule_items/user_sees_schedule_item_spec.rb
spec/system/schedule_item/user_sees_schedule_items_spec.rb

**Descrição**:
Adapta a aplicação para receber atividades não disponíveis 
- Adição de tributo na classe Curriculum
- Alteração da view
- Alteração de testes
View:
- Quando há atividades:
- Quando atividades não estão disponíveis:
- Quando não há nenhuma atividade para esta programação:
Resolve #181

Adição da disponibilidade de tarefas

---

app/assets/stylesheets/application.tailwind.css
app/views/shared/_feedback_form.html.erb
app/views/shared/_rating.html.erb
spec/system/feedbacks/user_add_feedback_spec.rb
spec/system/item_feedbacks/user_create_item_feedback_spec.rb

1. cria classes personalizadas de input e label para notas no tailwind;
2. cria componente reutilizável de notas de feedback por estrelas;
3. inclui rating no form de avaliação com lógica condicional de uso do valor de name a depender do model utilizado;
4. refatora testes para uso do rate de notas por estrelas;
Resolve #168

Adiciona rating de notas por estrelas nos feedbacks

---

app/controllers/api/v1/users_controller.rb
config/routes.rb
spec/requests/apis/users/users_api_spec.rb

Cria rota de api de usuários.
Recebe o CODE e retorna name, last_name, email e cpf.
Resolve #190

Cria rota de api de detalhes de um usuário

---

app/controllers/feedbacks_controller.rb
app/controllers/item_feedbacks_controller.rb
app/controllers/my_events_controller.rb
app/views/feedbacks/_feedback.html.erb
app/views/feedbacks/show.html.erb
app/views/item_feedbacks/_item_feedback.html.erb
app/views/item_feedbacks/show.html.erb
app/views/my_events/show.html.erb
config/locales/views/my_events/pt-BR.yml
config/routes.rb
spec/system/feedbacks/user_see_feedback_details_spec.rb
spec/system/item_feedbacks/user_see_item_feedback_spec.rb
spec/system/my_events/user_view_my_events_details_spec.rb

Adicionados testes, e feedback e item de feedback no feed
e tela de show no feed
Resolve #174

Adiciona feedback de item e de evento no feed

---

app/views/tickets/show.html.erb
spec/support/svg_helper.rb
spec/system/tickets/user_view_purchased_tickets_spec.rb

Refatora teste de QR CODE pra torná-lo mais completo

---

app/controllers/favorites_controller.rb
app/models/event.rb
app/models/user.rb
app/views/events/show.html.erb
config/locales/views/favorites/en.yml
config/locales/views/favorites/pt-BR.yml
spec/requests/favorites/user_create_favorites_request_spec.rb
spec/requests/favorites/user_delete_favorite_request_spec.rb

Cria método earliest_batch_date de eventos e has_event_reminder? para evitar repetição de código
Refatora controller de favorites para utilizar o método authenticate_user! do devise
Resolve #187

Refatora métodos repetitivos de usuário e eventos

---

Gemfile
README.md

README atualizado com as alterações feitas com o decorrer do projeto e gemfile organizado para ficar em ordem alfabética e em grupos padronizados.

Organizando o README e o arquivo do gemfile

---

app/views/events/_agenda.html.erb
app/views/events/show.html.erb
config/locales/views/events/en.yml
config/locales/views/events/pt-BR.yml
spec/system/events/user_sees_events_details_spec.rb
spec/system/events/visitant_sees_events_details_spec.rb

Refatora css da agenda na página de detalhes de evento

---

app/controllers/favorites_controller.rb
app/controllers/my_events_controller.rb
app/views/favorites/index.html.erb
app/views/my_events/index.html.erb
config/locales/views/favorites/en.yml
config/locales/views/favorites/pt-BR.yml
config/locales/views/my_events/en.yml
config/locales/views/my_events/pt-BR.yml
spec/system/favorites/user_view_favorites_spec.rb
spec/system/my_events/user_view_my_events_details_spec.rb

Adicionados condicionais para retornar erro do servidor quando a aplicação não esta no ar
Resolve #173

Removido bug na tela de detalhes do meus eventos o meus favoritos

---

app/controllers/item_feedbacks_controller.rb
app/views/feedback_answers/_feedback_answer.html.erb
app/views/item_feedbacks/show.html.erb
spec/system/item_feedbacks/user_see_item_feedback_spec.rb

Adicionado teste, lógica no controller e na tela de detalhes do feedback para permitir a resposta do palestrante.
Resolve #201

Usuario vê resposta do palestrante na tela de detalhes do feedback

---

app/views/feedbacks/index.html.erb
app/views/my_events/index.html.erb
config/locales/views/feedbacks/en.yml
config/locales/views/feedbacks/pt-BR.yml
config/locales/views/my_events/en.yml
config/locales/views/my_events/pt-BR.yml
spec/system/feedbacks/user_add_feedback_spec.rb
spec/system/feedbacks/user_see_feedbacks_spec.rb
spec/system/item_feedbacks/user_create_item_feedback_spec.rb

Adicionado CSS na tela de detalhes de feedback
Adicionado botão de acessar a meus feedbacks
Adicionados testes para a tela de detalhes de feedback
refatoração de testes de criação de feedback de eventos e atividades

Refatoração do listagem de feedback

---

app/views/shared/_rating.html.erb

Invertidos os valores das estrelas para corrigir erro na marcação da avaliação.
Resolve #205

Removido erro no mark

---

app/controllers/api/v1/tickets_controller.rb
spec/requests/apis/tickets/tickets_api_spec.rb
spec/system/profiles/links/user_add_new_social_link_spec.rb
spec/system/tickets/user_view_purchased_tickets_spec.rb

Bug corrigido na variável do event no else da api de tickets, agora ele puxa as informações do local correto e adicionado um teste em social links refletindo um caso de erro que não estava sendo coberto anteriormente.
Resolve #213

Bug endpoint tickets e teste adicionado em social links

---

app/controllers/schedule_items_controller.rb
app/models/curriculum.rb
app/models/task.rb
app/services/speakers_api_service.rb
app/views/schedule_items/show.html.erb
config/locales/views/schedule_items/en.yml
config/locales/views/schedule_items/pt-BR.yml
config/routes.rb
spec/factories/content.rb
spec/factories/curriculum.rb
spec/factories/task.rb
spec/models/curriculum_spec.rb
spec/models/task_spec.rb
spec/requests/schedule_items/user_sees_schedule_item_spec.rb
spec/services/speakers_api_service_spec.rb
spec/system/schedule_item/user_sees_schedule_items_spec.rb
spec/system/schedule_item/user_sees_task_of_schedule_item_spec.rb

Possibilita ao usuário finalizar uma tarefa

---

app/models/curriculum.rb
app/views/my_events/index.html.erb
app/views/schedule_items/show.html.erb
config/locales/views/schedule_items/en.yml
config/locales/views/schedule_items/pt-BR.yml
spec/factories/curriculum.rb
spec/models/curriculum_spec.rb
spec/requests/schedule_items/user_sees_schedule_item_spec.rb
spec/system/schedule_item/user_sees_schedule_items_spec.rb
spec/system/tickets/user_view_purchased_tickets_spec.rb

Cria funcionalidade de acesso ao certificado
Resolve #217

Cria renderização de link para acesso ao certificado

---

app/views/my_events/index.html.erb

style: mudança de estilização da vertical para a horizontal pag meus eventos

---

app/controllers/api/v1/feedback_answers_controller.rb
app/controllers/api/v1/item_feedbacks_controller.rb
app/controllers/item_feedbacks_controller.rb
app/models/item_feedback.rb
spec/requests/apis/item_feedback_answers/feedback_answers_api_spec.rb
spec/requests/apis/item_feedbacks/item_feedback_api_spec.rb
spec/system/item_feedbacks/user_see_item_feedback_spec.rb

Modificação de parâmetros da resposta do feedback, refatoração de testes e adicionado resposta do feedback a end point de listagem de feedback de um item 
Resolve #224

Refatoração endpoint de respota do feedback

---

app/controllers/dashboard_controller.rb
app/helpers/application_helper.rb
app/views/dashboard/index.html.erb
app/views/posts/_post.html.erb
config/locales/views/dashboard/en.yml
config/locales/views/dashboard/pt-BR.yml
spec/system/dashboard/user_view_dashboard_spec.rb

Alterações de CSS na página de dashboard e em seus respectivos testes e traduções.
Resolve #226

Alterações de CSS na página de dashboard e em seus respectivos testes e traduções.

---

app/views/announcements/_announcement_list_item.html.erb
spec/system/announcement/user_view_announcement_details_spec.rb

corrige problema de falta de renderização de estilo nos comunicados oficiais

---

app/services/events_api_service.rb
db/seeds.rb
spec/models/announcements_spec.rb
spec/models/batch_spec.rb
spec/models/event_spec.rb
spec/services/events_api_service_spec.rb
spec/support/json/error_events_list.json
spec/support/json/events_for_sale_list.json
spec/support/json/events_list.json

Alterações pontuais para adequar a aplicação para apresentação aos clientes.
- Criação de Seed
- Alteração de testes

Alterações para se adequar a apresentação
